
package presentation;

import entety.Course;
import entety.CourseSchedule;
import entety.Student;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import repository.CourseData;
import rojeru_san.complementos.RSTableMetro;

import service.CourseService;
import service.StudentService;

public class MyCourses extends javax.swing.JFrame {
     Student user;
     String courseName; // selected course from table
     CourseService courseService;
     StudentService studentService;
   
    public MyCourses(Student user) {
        this.user=user;  
        courseService=new CourseService();
        studentService=new StudentService();
        initComponents();
        txtUsername.setText(user.getUsername());
        setLocationRelativeTo(null);
        setVisible(true);
        showMyCourses();
        courseDetailsPanel.setVisible(false);
    }
    
   //for testing purposes
    public MyCourses() {
 
        courseService=new CourseService();
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        showMyCourses();
        courseDetails.setVisible(false);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        myCourses = new javax.swing.JButton();
        browseCourses = new javax.swing.JButton();
        topCourses = new javax.swing.JButton();
        courseCalendar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new rojeru_san.complementos.RSTableMetro();
        courseDetailsPanel = new javax.swing.JTabbedPane();
        courseDetails = new javax.swing.JPanel();
        txtLecturer = new javax.swing.JLabel();
        txtSchedule = new javax.swing.JLabel();
        txtLocation = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JLabel();
        txtNoStudents = new javax.swing.JLabel();
        btnJoinDrop = new javax.swing.JButton();
        viewFeedbacksButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaFeedback = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtCourseRating = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        submitFeedbackButton = new javax.swing.JButton();
        submitRatingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 30, 40));

        txtUsername.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user (3).png"))); // NOI18N
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 140, 60));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book-stack.png"))); // NOI18N
        jLabel1.setText(" Course Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 320, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 90));

        jPanel2.setBackground(new java.awt.Color(153, 193, 250));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(51, 0, 153));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home (1).png"))); // NOI18N
        Home.setText("Home");
        Home.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        myCourses.setBackground(new java.awt.Color(255, 255, 255));
        myCourses.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        myCourses.setForeground(new java.awt.Color(51, 0, 153));
        myCourses.setText("My Courses");
        myCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        myCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCoursesActionPerformed(evt);
            }
        });

        browseCourses.setBackground(new java.awt.Color(255, 255, 255));
        browseCourses.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        browseCourses.setForeground(new java.awt.Color(51, 0, 153));
        browseCourses.setText("Browse Courses");
        browseCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        browseCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCoursesActionPerformed(evt);
            }
        });

        topCourses.setBackground(new java.awt.Color(255, 255, 255));
        topCourses.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        topCourses.setForeground(new java.awt.Color(51, 0, 153));
        topCourses.setText("Top Courses");
        topCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        topCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topCoursesActionPerformed(evt);
            }
        });

        courseCalendar.setBackground(new java.awt.Color(255, 255, 255));
        courseCalendar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        courseCalendar.setForeground(new java.awt.Color(51, 0, 153));
        courseCalendar.setText(" Courses Calendar");
        courseCalendar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        courseCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(myCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(browseCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(topCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courseCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblCourse.setBackground(new java.awt.Color(255, 255, 255));
        tblCourse.setForeground(new java.awt.Color(51, 51, 51));
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "My courses"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.setAlignmentY(1.0F);
        tblCourse.setColorBackgoundHead(new java.awt.Color(204, 0, 153));
        tblCourse.setColorFilasBackgound2(new java.awt.Color(255, 204, 255));
        tblCourse.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblCourse.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblCourse.setColorSelBackgound(new java.awt.Color(255, 153, 255));
        tblCourse.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        tblCourse.setRowHeight(40);
        tblCourse.setSelectionBackground(new java.awt.Color(0, 51, 51));
        tblCourse.setShowGrid(false);
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        courseDetailsPanel.setBackground(new java.awt.Color(204, 0, 153));
        courseDetailsPanel.setForeground(new java.awt.Color(255, 255, 255));
        courseDetailsPanel.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N

        courseDetails.setBackground(new java.awt.Color(255, 255, 255));
        courseDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(40, 1, 1, 1, new java.awt.Color(153, 204, 255)));

        txtLecturer.setBackground(new java.awt.Color(255, 255, 255));
        txtLecturer.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtLecturer.setForeground(new java.awt.Color(51, 51, 51));
        txtLecturer.setText("Lecturer: ");

        txtSchedule.setBackground(new java.awt.Color(204, 204, 255));
        txtSchedule.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtSchedule.setForeground(new java.awt.Color(51, 51, 51));
        txtSchedule.setText("Schedule");

        txtLocation.setBackground(new java.awt.Color(204, 204, 255));
        txtLocation.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(51, 51, 51));
        txtLocation.setText("Location:");

        txtCourseName.setBackground(new java.awt.Color(204, 204, 255));
        txtCourseName.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        txtCourseName.setForeground(new java.awt.Color(153, 204, 255));
        txtCourseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtNoStudents.setBackground(new java.awt.Color(204, 204, 255));
        txtNoStudents.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtNoStudents.setForeground(new java.awt.Color(51, 51, 51));
        txtNoStudents.setText("Number of students");

        btnJoinDrop.setBackground(new java.awt.Color(153, 204, 255));
        btnJoinDrop.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnJoinDrop.setForeground(new java.awt.Color(255, 255, 255));
        btnJoinDrop.setText("jButton1");
        btnJoinDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinDropActionPerformed(evt);
            }
        });

        viewFeedbacksButton.setBackground(new java.awt.Color(153, 204, 255));
        viewFeedbacksButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        viewFeedbacksButton.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbacksButton.setText("View Feedbacks");
        viewFeedbacksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbacksButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout courseDetailsLayout = new javax.swing.GroupLayout(courseDetails);
        courseDetails.setLayout(courseDetailsLayout);
        courseDetailsLayout.setHorizontalGroup(
            courseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(courseDetailsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnJoinDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewFeedbacksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(courseDetailsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        courseDetailsLayout.setVerticalGroup(
            courseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNoStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(courseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewFeedbacksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        courseDetailsPanel.addTab("Course Details", courseDetails);

        jPanel4.setBackground(new java.awt.Color(255, 186, 220));

        txtAreaFeedback.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaFeedback.setColumns(20);
        txtAreaFeedback.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtAreaFeedback.setForeground(new java.awt.Color(51, 51, 51));
        txtAreaFeedback.setLineWrap(true);
        txtAreaFeedback.setRows(5);
        txtAreaFeedback.setWrapStyleWord(true);
        txtAreaFeedback.setAutoscrolls(false);
        txtAreaFeedback.setMaximumSize(new java.awt.Dimension(100, 400));
        jScrollPane2.setViewportView(txtAreaFeedback);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 153));
        jLabel2.setText("Rate Course");

        txtCourseRating.setBackground(new java.awt.Color(255, 255, 255));
        txtCourseRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No rating", "1", "2", "3", "4", "5", " " }));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("Write you feedback here");

        submitFeedbackButton.setBackground(new java.awt.Color(204, 0, 153));
        submitFeedbackButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        submitFeedbackButton.setForeground(new java.awt.Color(255, 255, 255));
        submitFeedbackButton.setText("Submit feedback");
        submitFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFeedbackButtonActionPerformed(evt);
            }
        });

        submitRatingButton.setBackground(new java.awt.Color(204, 0, 153));
        submitRatingButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        submitRatingButton.setForeground(new java.awt.Color(255, 255, 255));
        submitRatingButton.setText("Submit Rating");
        submitRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRatingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCourseRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitRatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(submitFeedbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitFeedbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        courseDetailsPanel.addTab("Leave feedback", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(courseDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 1110, 710));

        setSize(new java.awt.Dimension(1288, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Home home=new Home(user);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void myCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCoursesActionPerformed
        
    }//GEN-LAST:event_myCoursesActionPerformed

    private void browseCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCoursesActionPerformed
        BrowseCourses allCoursesPage=new BrowseCourses(user);
        this.setVisible(false);
    }//GEN-LAST:event_browseCoursesActionPerformed

    private void topCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topCoursesActionPerformed

    private void courseCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCalendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseCalendarActionPerformed

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
   
        int row=tblCourse.getSelectedRow();
        TableModel model=tblCourse.getModel();
        courseName=model.getValueAt(row,0).toString();
        showCourseDetails(courseName);
        showReview(courseName);
        courseDetailsPanel.setVisible(true);
    }//GEN-LAST:event_tblCourseMouseClicked

    private void btnJoinDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinDropActionPerformed

        if(studentService.followsCourses(user, courseName))
        studentService.dropCourse(user, courseName);
        else studentService.joinCourse(user, courseName);
        showCourseDetails(courseName);
        
    }//GEN-LAST:event_btnJoinDropActionPerformed

    private void submitFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFeedbackButtonActionPerformed
        updateFeedback();  
    }//GEN-LAST:event_submitFeedbackButtonActionPerformed

    private void viewFeedbacksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFeedbacksButtonActionPerformed
        Reviews feedbackpage=new Reviews(user,courseName);
        this.setVisible(false);
    }//GEN-LAST:event_viewFeedbacksButtonActionPerformed

    private void submitRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRatingButtonActionPerformed
        updateRating();
    }//GEN-LAST:event_submitRatingButtonActionPerformed

  

    public void showMyCourses() {
      List<Course> courses = courseService.getStudentCourses(user.getUsername());
      DefaultTableModel model=(DefaultTableModel) tblCourse.getModel();
    
      for (Course course : courses) {
          String[] row = { course.getName() };
          
          model.addRow(row);
      }
     
      }
    
    public void showCourseDetails(String name){
        Course course=courseService.getCourseDetails(name);
        txtCourseName.setText(name);
        txtLecturer.setText("Lecturer: "+course.getInstructor());
        txtLocation.setText("Location: "+course.getLocation());
        
        List<CourseSchedule> courseSchedule=courseService.getCourseSchedule(name);
        txtSchedule.setText("Schedule: ");;
        for(CourseSchedule schedule: courseSchedule ){
            txtSchedule.setText(txtSchedule.getText()+schedule.getMeetingDay()+" "
                    + schedule.getStartTime()+"-"+schedule.getEndTime()+"   ");
        }
        
        txtNoStudents.setText("Number of students: "+courseService.getNoStudents(name));
        
        if(studentService.followsCourses(user, name))
            btnJoinDrop.setText("Drop Course");
        else btnJoinDrop.setText("Join Course");; 
    }
    
    
    public void  showReview(String courseName){
        int rating=studentService.getRating(user, courseName);
        String feebback=studentService.getFeedback(user, courseName);
        txtCourseRating.setSelectedIndex(rating);
        txtAreaFeedback.setText(feebback);
    }
    
    public void updateRating(){
        int rating=txtCourseRating.getSelectedIndex();
        
        studentService.rateCourse(user, courseName,rating);
    }
    
    public void updateFeedback(){
        String feedback=txtAreaFeedback.getText();
        studentService.leaveFeeback(user, courseName, feedback);
    }
    
    
        public static void main(String args[]) {
       
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Home;
    private javax.swing.JButton browseCourses;
    private javax.swing.JButton btnJoinDrop;
    private javax.swing.JButton courseCalendar;
    private javax.swing.JPanel courseDetails;
    private javax.swing.JTabbedPane courseDetailsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton myCourses;
    private javax.swing.JButton submitFeedbackButton;
    private javax.swing.JButton submitRatingButton;
    private rojeru_san.complementos.RSTableMetro tblCourse;
    private javax.swing.JButton topCourses;
    private javax.swing.JTextArea txtAreaFeedback;
    private javax.swing.JLabel txtCourseName;
    private javax.swing.JComboBox<String> txtCourseRating;
    private javax.swing.JLabel txtLecturer;
    private javax.swing.JLabel txtLocation;
    private javax.swing.JLabel txtNoStudents;
    private javax.swing.JLabel txtSchedule;
    private javax.swing.JLabel txtUsername;
    private javax.swing.JButton viewFeedbacksButton;
    // End of variables declaration//GEN-END:variables
}
